# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6e70fc67849f21fba8a7f1e52500333a8ad0d783546f0a3dcd3d8aaa1e07464525b7cb11f9a552bfc615a76107024630909bde6f68266891232688b95a5a1d

test:
  secret_key_base: cc4e7d398cec82f880106507c8786729c054184c304114479eb7bd2a28324bf00e4174d732a255e1a31caeaf2d13ce1b4f518abbcfd4a85818ca2859f966c8a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
